name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Reference the DockerHub username secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # Reference the DockerHub password secret

      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/your-app:latest .

      - name: Push Docker image to DockerHub
        run: |
          docker push your-dockerhub-username/your-app:latest
